[versions]

[libraries]
boilerplate = "org.danilopianini:boilerplate:0.2.2"
commons-lang3 = "org.apache.commons:commons-lang3:3.14.0"
guava = "com.google.guava:guava:33.1.0-jre"
jgrapht-core = "org.jgrapht:jgrapht-core:1.5.2"
junit4 = "junit:junit:4.13.2"
spotbugs-annotations = "com.github.spotbugs:spotbugs-annotations:4.8.4"

[plugins]
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "3.1.4" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.61.0" }
java-qa = { id = "org.danilopianini.gradle-java-qa", version = "1.43.0" }
multiJvmTesting = { id = "org.danilopianini.multi-jvm-test-plugin", version = "0.5.8" }
publishOnCentral = { id = "org.danilopianini.publish-on-central", version = "5.0.26" }
taskTree = { id = "com.dorongold.task-tree", version = "3.0.0" }
