[versions]

[libraries]
boilerplate = "org.danilopianini:boilerplate:0.2.2"
commons-lang3 = "org.apache.commons:commons-lang3:3.12.0"
guava = "com.google.guava:guava:31.1-jre"
jgrapht-core = "org.jgrapht:jgrapht-core:1.5.1"
junit4 = "junit:junit:4.13.2"
spotbugs-annotations = "com.github.spotbugs:spotbugs-annotations:4.7.3"

[plugins]
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "1.1.2" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.35.0" }
java-qa = { id = "org.danilopianini.gradle-java-qa", version = "0.44.0" }
multiJvmTesting = { id = "org.danilopianini.multi-jvm-test-plugin", version = "0.4.17" }
publishOnCentral = { id = "org.danilopianini.publish-on-central", version = "3.3.0" }
taskTree = { id = "com.dorongold.task-tree", version = "2.1.1" }
